### PR TITLE
ard-reset-arduino: support pyserial 3.0

### LINKED ISSUE #407: ard-reset-arduino does not work with pyserial 3.0
It seems that setBaudRate() is gone in the new pyserial api:

```
Resetting Arduino...
/usr/bin/ard-reset-arduino --caterina  /dev/ttyACM0
Traceback (most recent call last):
  File "/usr/bin/ard-reset-arduino", line 20, in <module>
    ser.setBaudrate(1200)
AttributeError: 'Serial' object has no attribute 'setBaudrate'
/usr/share/arduino/Arduino.mk:1442: recipe for target 'reset' failed
make: *** [reset] Error 1
```

### PR DESCRIPTION
**Pull request by gauteh**
Fix #407

### CODE REVIEW

**Comment by sudar** [comment]
@gauteh 

Thanks for the fix.

Travis build is failing for this PR. I am not sure if this is really related to your fix. I will merge it once figuring out why Travis build failed.

**Comment by sudar** [comment]
Also, can you add a note about it in the [History.md](https://github.com/sudar/Arduino-Makefile/blob/master/HISTORY.md) file as well?

**Comment by gauteh** [comment]
Added, travis error seems unrelated.

-g.

**Comment by sudar** [comment]
Thanks. Just merged it.

**Comment by michaelbaisch** [comment]
I had some trouble with this commit.
`AttributeError: 'Serial' object has no attribute 'setBaudRate'`
Looks like the function is called "setBaudrate" and not "setBaudRate", notice the "R".

**Comment by gauteh** [comment]
Oops, my bad, this should fix it: https://github.com/gauteh/Arduino-Makefile/commit/03f5852f2dd34476ba833656593af8b4658ffbd3

**Comment by sudar** [comment]
@gauteh 

Can you send me a PR for the new change?
