### ISSUE TITLE
ard-reset-arduino does not work with pyserial 3.0

### ISSUE THREAD

**Issue by gauteh** [sudar/Arduino-Makefile#407]
It seems that setBaudRate() is gone in the new pyserial api:

```
Resetting Arduino...
/usr/bin/ard-reset-arduino --caterina  /dev/ttyACM0
Traceback (most recent call last):
  File "/usr/bin/ard-reset-arduino", line 20, in <module>
    ser.setBaudrate(1200)
AttributeError: 'Serial' object has no attribute 'setBaudrate'
/usr/share/arduino/Arduino.mk:1442: recipe for target 'reset' failed
make: *** [reset] Error 1
```
